# Generated by Django 6.0.1 on 2026-04-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mainuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/blank_profile_picture.png', null=True, upload_to='profile_pics/'),
        ),
    ]
